apiVersion: v1
kind: Namespace
metadata:
  name: semantic-search
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-pvc
  namespace: semantic-search
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-standalone
  namespace: semantic-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus-standalone
  template:
    metadata:
      labels:
        app: milvus-standalone
    spec:
      containers:
        - name: milvus
          image: milvusdb/milvus:2.4.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MILVUS_DEPLOY_MODE
              value: standalone
          ports:
            - containerPort: 19530
            - containerPort: 9091
          volumeMounts:
            - name: milvus-data
              mountPath: /var/lib/milvus
      volumes:
        - name: milvus-data
          persistentVolumeClaim:
            claimName: milvus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: semantic-search
spec:
  selector:
    app: milvus-standalone
  ports:
    - name: grpc
      port: 19530
      targetPort: 19530
    - name: metrics
      port: 9091
      targetPort: 9091
  type: ClusterIP