apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: semantic-search-milvus
  annotations:
    description: "Semantic search app using Milvus with FastAPI"
parameters:
  - name: NAMESPACE
    value: semantic-search
  - name: IMAGE
    value: ghcr.io/your-org/semantic-search-milvus:latest
  - name: HOST
    value: semantic-search.apps.example.com
objects:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ${NAMESPACE}

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: milvus-pvc
      namespace: ${NAMESPACE}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: milvus-standalone
      namespace: ${NAMESPACE}
    spec:
      replicas: 1
      selector:
        matchLabels: { app: milvus-standalone }
      template:
        metadata:
          labels: { app: milvus-standalone }
        spec:
          containers:
            - name: milvus
              image: milvusdb/milvus:2.4.7
              env:
                - name: MILVUS_DEPLOY_MODE
                  value: standalone
              ports:
                - containerPort: 19530
                - containerPort: 9091
              volumeMounts:
                - name: data
                  mountPath: /var/lib/milvus
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: milvus-pvc

  - apiVersion: v1
    kind: Service
    metadata:
      name: milvus
      namespace: ${NAMESPACE}
    spec:
      selector:
        app: milvus-standalone
      ports:
        - name: grpc
          port: 19530
          targetPort: 19530
        - name: metrics
          port: 9091
          targetPort: 9091
      type: ClusterIP

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: semantic-search-app
      namespace: ${NAMESPACE}
    spec:
      replicas: 1
      selector:
        matchLabels: { app: semantic-search-app }
      template:
        metadata:
          labels: { app: semantic-search-app }
        spec:
          containers:
            - name: app
              image: ${IMAGE}
              env:
                - name: MILVUS_HOST
                  value: milvus.${NAMESPACE}.svc.cluster.local
                - name: MILVUS_PORT
                  value: "19530"
                - name: MODEL_DIR
                  value: /models/all-MiniLM-L6-v2-onnx
                - name: EMBEDDING_DIM
                  value: "384"
                - name: INDEX_TYPE
                  value: "IVF_FLAT"
                - name: METRIC_TYPE
                  value: "L2"
                - name: ORT_PROVIDER
                  value: "AUTO"
              ports:
                - containerPort: 8000
              volumeMounts:
                - name: model-volume
                  mountPath: /models/all-MiniLM-L6-v2-onnx
                  readOnly: true
          volumes:
            - name: model-volume
              emptyDir: {}

  - apiVersion: v1
    kind: Service
    metadata:
      name: semantic-search-app
      namespace: ${NAMESPACE}
    spec:
      selector:
        app: semantic-search-app
      ports:
        - name: http
          port: 80
          targetPort: 8000
      type: ClusterIP

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: semantic-search
      namespace: ${NAMESPACE}
    spec:
      host: ${HOST}
      to:
        kind: Service
        name: semantic-search-app
        weight: 100
      port:
        targetPort: http